{% set name = "siuba" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/machow/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1c567097680042b04af690ba175ce91fefb89c5ff258c41c4497af4c9c445c7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.12.0
    - pandas >=0.24.0
    - python >=3.7
    - pyyaml >=3.0.0
    - sqlalchemy >=1.2.19

test:
  imports:
    - siuba
    - siuba.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/machow/siuba
  summary: A package for quick, scrappy analyses with pandas and SQL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://siuba.readthedocs.io/
  dev_url: https://github.com/machow/siuba

extra:
  recipe-maintainers:
    - philip-khor
