{% set name = "siuba" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/machow/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5a5e64bcf04ab73ed360caa144d7fba28c234678b94761addced485b22609055

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.12.0
    - pandas >=0.24.0,<2.1.0
    - python >={{ python_min }}
    - pyyaml >=3.0.0
    - sqlalchemy >=1.2.19

test:
  imports:
    - siuba
    - siuba.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/machow/siuba
  summary: A package for quick, scrappy analyses with pandas and SQL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://siuba.readthedocs.io/
  dev_url: https://github.com/machow/siuba

extra:
  recipe-maintainers:
    - philip-khor
